//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comprobante()
        {
            this.detalleComprobante = new HashSet<detalleComprobante>();
        }
    
        public int id { get; set; }
        public int serie { get; set; }
        public string glosa { get; set; }
        public System.DateTime fecha { get; set; }
        public double tipoCambio { get; set; }
        public int estado { get; set; }
        public int tipoComprobante { get; set; }
        public int idUsuario { get; set; }
        public int idMoneda { get; set; }
        public int idEmpresa { get; set; }
    
        public virtual moneda moneda { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleComprobante> detalleComprobante { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
