//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuenta()
        {
            this.cuenta1 = new HashSet<cuenta>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public int nivel { get; set; }
        public int tipocuenta { get; set; }
        public int estado { get; set; }
        public int idUsuario { get; set; }
        public int idEmpresa { get; set; }
        public Nullable<int> idCuentaPadre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuenta> cuenta1 { get; set; }
        public virtual cuenta cuenta2 { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
