//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleNota
    {
        public int idArticulo { get; set; }
        public int nroLote { get; set; }
        public int idNota { get; set; }
        public int cantidad { get; set; }
        public double precioVenta { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual nota nota { get; set; }
        public virtual nota nota1 { get; set; }
    }
}
