//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresaMoneda
    {
        public int id { get; set; }
        public Nullable<double> cambio { get; set; }
        public Nullable<int> activo { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int idEmpresa { get; set; }
        public int idMonedaPrincipal { get; set; }
        public Nullable<int> idMonedaAlternativa { get; set; }
        public int idUsuario { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual moneda moneda { get; set; }
        public virtual moneda moneda1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
