//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodo
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechainicio { get; set; }
        public System.DateTime fechafin { get; set; }
        public int idUsuario { get; set; }
        public int idGestion { get; set; }
        public int estado { get; set; }
    
        public virtual gestion gestion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
